### ISSUE TITLE
Speller is not built

### ISSUE THREAD

**Issue by Trondtr** [giellalt/lang-nno#2]
Configuration:
 ./configure --with-hfst --with-xfst --enable-reversed-intersect --enable-spellers

Result for fst: Everything is ok, it compiles:
tf4-hsl-m0024:lang-nno trond$ lt src/generator-gt-desc.hfstol 
-rw-r--r--  1 trond  staff  10362821 24 sep 09:14 src/generator-gt-desc.hfstol

But the speller is not built, despite the configuration. No nn.zhfst or the like.

Error message when building:
make V=1
(...)
Making check in weights
make[3]: Nothing to be done for `check'.
Making check in .
  GEN      Mozvoikko2-fo.xpi
zip I/O error: Permission denied
zip error: Could not create output file (../../Mozvoikko2-fo.xpi)
(...)
Making all in spellcheckers
Making all in filters
Makefile:1010: target `remove-word-boundary.xfst' doesn't match the target pattern
Makefile:1010: target `remove-usage-tags.xfst' doesn't match the target pattern
"/usr/local/bin/hfst-regexp2fst"  \
	   --format=openfst-tropical \
		"--xerox-composition=ON" -v -S -i  -o remove-word-boundary.xfst
/usr/local/bin/hfst-regexp2fst: Could not open '-o'. No such file or directory
make[3]: *** [remove-word-boundary.xfst] Error 1

**Comment by snomos** [comment]
> `GEN Mozvoikko2-fo.xpi zip I/O error: Permission denied`

This is the clue: .the file has been built using `sudo`, thus non-sudo `make` can't overwrite the file, thus make errors out. Manually remove the file, and retry. Should work.
