### ISSUE TITLE
The model does not compile

### ISSUE THREAD

**Issue by trondtynnol** [giellalt/lang-nno#4]
Trying to compile with the default configuration gives the error 
```
make[3]: Entering directory '/home/trond/gt/giellalt/lang-nno/src/fst/incoming'
make[3]: *** No rule to make target 'ordbank_nn/fullform_nn.txt', needed by 'fullform.utf8.txt'.  Stop.
```
I am not sure if this model is even used, as we have the `lang-nno-x-ext-apertium` which works. Should we consider pointing users to the Apertium version?

**Comment by snomos** [comment]
I will update the README file to reflect the source and usability of this repo, which is:

- it is an experiment, it is not suited for general use
- it uses data from Språkbanken
- it has no components for dynamic compounding

So yes, people should use the apertium variant, although that variant has some issues on its own. The main issue is that the difference between normative and descriptive is only indirectly encoded, and that makes it hard to extract the lexicon we want for our use.
